### ISSUE TITLE
Question about the edge during the graph construction

### ISSUE THREAD

**Issue by Puzzled-Hui** [seung-lab/dijkstra3d#23]
Hi, I am very interested in your work! I want to ask a question about the graph construction, For example, a 3*3*3 cube with 26-connectivity, it should has 54 edges to weight, how can i use this repo to implement this?

**Comment by william-silversmith** [comment]
Hi! Thanks for being interested in dijkstra3d!

This repo has two modes of operation. It supports:
1) 6, 18, and 26 connected 3D images with undirected edges where the "destination" vertex contains the edge weight.
2) The above, but supported by a connectivity graph that enables you to designate certain directed edges as impassable. 

Do either of these situations sounds like your use case?

**Comment by Puzzled-Hui** [comment]
> Hi! Thanks for being interested in dijkstra3d!
> 
> This repo has two modes of operation. It supports:
> 
> 1. 6, 18, and 26 connected 3D images with undirected edges where the "destination" vertex contains the edge weight.
> 2. The above, but supported by a connectivity graph that enables you to designate certain directed edges as impassable.
> 
> Do either of these situations sound like your use case?

Thanks for your reply! I wanna further know if an vertex are two or more edges' destination, while this two edge shares different weight, how can i handle this situation?

**Comment by william-silversmith** [comment]
I think if I understand your question correctly, this mode of operation is not supported. We only support a single edge weight for a given destination vertex. This library was written for a certain use case that can take advantage of this kind of optimization. It's not intended to be a fully general graph library.

For full graph handling, I'd recommend looking at one of these:
- https://igraph.org/
- https://networkx.org/
- https://graph-tool.skewed.de/

Of them, networkx is probably the easiest to use and install, but also the slowest.

**Comment by Puzzled-Hui** [comment]
> I think if I understand your question correctly, this mode of operation is not supported. We only support a single edge weight for a given destination vertex. This library was written for a certain use case that can take advantage of this kind of optimization. It's not intended to be a fully general graph library.
> 
> For full graph handling, I'd recommend looking at one of these:
> 
> * https://igraph.org/
> * https://networkx.org/
> * https://graph-tool.skewed.de/
> 
> Of them, networkx is probably the easiest to use and install, but also the slowest.

Thanks for your detailed and generous reply ! : )

**Comment by william-silversmith** [comment]
No problem! Hope it was helpful.
