### ISSUE TITLE
Path from parents does not work for 2d data

### ISSUE THREAD

**Issue by yanlend** [seung-lab/dijkstra3d#24]
`path_from_parents` implicitly assumes 3d input data and fails for 2d data.
The code access [`shape[2]`](https://github.com/seung-lab/dijkstra3d/blob/f8c822e56f4f3edaa667161c583babefc56e9ee6/dijkstra3d.pyx#L252) argument even though `ndim` is only 2.

This might be an easy fix to check for the dimensionality of the input array, and the related functions seem to support both 2d and 3d input.

**Comment by william-silversmith** [comment]
Hi, I wrote a fix for this issue. Thanks for reporting! Would you mind taking a look and checking that it performs the way you expect? Thanks!

**Comment by yanlend** [comment]
Sorry did not have time on short notice to compile and test it.

Thank you for the quick fix!
