### ISSUE TITLE
Shortest path is not following the original data

### ISSUE THREAD

**Issue by patialaghos** [seung-lab/dijkstra3d#36]
![loop_pic](https://user-images.githubusercontent.com/111475350/185544893-cda8b711-5db1-4daf-927d-7d2ff35a7af1.png)

I was trying to find the shortest path between two terminals of a skeletonized 3D data. Here is my code - 

```python
p = sio.loadmat('loop') # Load data
p = p['d']

tps = terminals(p, np.argwhere(p==1)) # Get terminals

path = dijkstra3d.dijkstra(p, tps[0], tps[1], connectivity=26, bidirectional=True)  # Apply Dijkstra3d

d = np.zeros(p.shape, p.dtype)

d[path[:,0], path[:,1], path[:,2]] = 1
d[tps[0][0], tps[0][1], tps[0][2]] = 5
d[tps[1][0], tps[1][1], tps[1][2]] = 5
```
But when I visualize the path, it seems that it is not following the 3D data, rather jumping out from one terminal to another terminal.

I have attached an image where red is the shortest path returned by `dijkstra3d` and grey is the original 3D data.

**Comment by william-silversmith** [comment]
Hi, this could be a result of inverted foreground/background. What are the values in `p`?

**Comment by patialaghos** [comment]
It is a 3D binary image where background is assigned to 0 and the line is represented by 1. But the line is a connected component. There is no disconnection between the terminal points.

**Comment by william-silversmith** [comment]
Hi patialaghos, this is what I thought. The cost of moving between pixels are the values. So 0 means there is no cost to move and 1 means there is 1 cost to move. Perhaps I should have a binary image function that would be more intuitive, but the way to fix this is to set all 0 voxels equal to NUM_PIXELS+1 so that the cost of moving to a background pixel is larger than any possible route on the image.

**Comment by patialaghos** [comment]
Yes, that's what I did. I replace the background pixels with some higher value. Looks like it is working fine now. Thank you very much for your great support.

**Comment by william-silversmith** [comment]
Fantastic! Glad I was able to help.
