### ISSUE TITLE
euclidean_distance_field documentation example not working

### ISSUE THREAD

**Issue by alexisthual** [seung-lab/dijkstra3d#37]
Hi!
Thank you for the nice package :)

I just tried using the code snippet in the readme and it seems that `euclidean_distance_field()` only accepts `np.int8` inputs.
I am using the latest version of `dijkstra3d` (1.12.0) and installed it with `pip`.
Any other data type (like `np.int32`) will raise an error of the following form:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/home/alexis/singbrain/repo/alexis_thual/_134_lmds_on_volumes.py](https://file+.vscode-resource.vscode-cdn.net/home/alexis/singbrain/repo/alexis_thual/_134_lmds_on_volumes.py) in ()
      [25](file:///home/alexis/singbrain/repo/alexis_thual/_134_lmds_on_volumes.py?line=24) # %%
----> [26](file:///home/alexis/singbrain/repo/alexis_thual/_134_lmds_on_volumes.py?line=25) dist_field = dijkstra3d.euclidean_distance_field(field, source=source)
      [27](file:///home/alexis/singbrain/repo/alexis_thual/_134_lmds_on_volumes.py?line=26) dist_field.shape

File dijkstra3d.pyx:520, in dijkstra3d.euclidean_distance_field()

File dijkstra3d.pyx:1345, in dijkstra3d._execute_euclidean_distance_field()

TypeError: Type int32 not currently supported.
```

I think the code snippet should be changed to reflect this requirement.
Maybe it is worth documenting and / or bugfixing as well?

Tagging @pbarbarant who is also interested in this!

**Comment by william-silversmith** [comment]
Hi Alexis, thanks for writing in! Since the accepted field is boolean, the accepted types are bool, np.int8, and np.uint8 (since they can be interpreted as views of each other). Larger datatypes could be supported, but would be wasteful. Would you still like the function updated to accept more types? I can certainly update the documentation in the README.

**Comment by alexisthual** [comment]
Oh I see, thank you for the quick answer!
Indeed, I don't think supporting more data types is needed: updating the docs should be enough 😊
